name: skyenv
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anaconda-anon-usage=0.5.0
  - annotated-types=0.6.0
  - anyio=4.7.0
  - archspec=0.2.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - boltons=24.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - conda=25.1.1
  - conda-anaconda-telemetry=0.1.2
  - conda-anaconda-tos=0.1.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.1.1
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cpp-expected=1.1.0
  - cryptography=43.0.3
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distro=1.9.0
  - executing=0.8.3
  - expat=2.6.4
  - fmt=9.1.0
  - frozendict=2.4.2
  - h11=0.16.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - icu=73.1
  - idna=3.7
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.9.25
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libarchive=3.7.7
  - libcurl=8.11.1
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmamba=2.0.5
  - libmambapy=2.0.5
  - libnghttp2=1.57.0
  - libsodium=1.0.18
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - menuinst=2.2.0
  - mistune=3.1.2
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.2
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - openssl=3.0.16
  - overrides=7.4.0
  - packaging=24.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pip=25.0
  - platformdirs=3.10.0
  - pluggy=1.5.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.12.9
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - referencing=0.30.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.22.3
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - send2trash=1.8.2
  - setuptools=75.8.0
  - simdjson=3.10.1
  - six=1.17.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - spdlog=1.11.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.4.0
  - tk=8.6.14
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - truststore=0.10.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.4.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiobotocore==2.23.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - base58==2.1.1
      - boto3==1.38.27
      - botocore==1.38.27
      - cartopy==0.24.1
      - cdsapi==0.7.6
      - cfgrib==0.9.15.0
      - click==8.1.8
      - contourpy==1.3.2
      - crc32c==2.7.1
      - cycler==0.12.1
      - donfig==0.8.1.post1
      - dotenv==0.9.9
      - eccodes==2.41.0
      - ecmwf-datastores-client==0.2.0
      - ecmwf-opendata==0.3.19
      - filelock==3.18.0
      - findlibs==0.1.1
      - flatbuffers==25.2.10
      - fonttools==4.58.4
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - grpclib==0.4.7
      - h2==4.2.0
      - hf-xet==1.1.5
      - hpack==4.1.0
      - huggingface-hub==0.33.0
      - hyperframe==6.1.0
      - imageio==2.37.0
      - jh2==5.0.9
      - jmespath==1.0.1
      - kiwisolver==1.4.8
      - loguru==0.7.3
      - matplotlib==3.10.3
      - meteostat==1.7.1
      - modal==1.0.4
      - multidict==6.5.0
      - multiurl==0.3.5
      - niquests==3.14.1
      - numcodecs==0.16.1
      - numpy==2.3.1
      - openmeteo-requests==1.5.0
      - openmeteo-sdk==1.20.1
      - pandas==2.3.0
      - pillow==11.2.1
      - propcache==0.3.2
      - protobuf==6.31.1
      - psycopg2-binary==2.9.10
      - pyparsing==3.2.3
      - pyproj==3.7.1
      - pyshp==2.3.1
      - python-dotenv==1.0.1
      - pytz==2025.2
      - qh3==1.5.3
      - s3fs==0.4.2
      - s3transfer==0.13.0
      - scipy==1.15.3
      - shapely==2.1.1
      - shellingham==1.5.4
      - sigtools==4.0.1
      - skyrim==0.0.2
      - synchronicity==0.9.16
      - toml==0.10.2
      - typer==0.16.0
      - types-certifi==2021.10.8.3
      - types-toml==0.10.8.20240310
      - tzdata==2025.2
      - urllib3-future==2.12.922
      - wassima==1.2.2
      - watchfiles==1.1.0
      - wrapt==1.17.2
      - xarray==2025.6.1
      - yarl==1.20.1
      - zarr==3.0.8
